#

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: eonwyn.lan




rule_files:
  - /etc/prom.config/rules/*.rules

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - eonwyn:9093


scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - labels:
        dev: eonwyn
        env: prod
      targets:
      - eonwyn:9090
  - job_name: node
    metrics_path: /metrics
    static_configs:
    - labels:
        dev: eonwyn
        env: prod
      targets:
      - eonwyn:9100
  - job_name: nginx
    metrics_path: /metrics
    static_configs:
    - labels:
        dev: eonwyn
        env: prod
      targets:
      - eonwyn:9145
  - job_name: router
    metrics_path: /metrics
    static_configs:
    - labels:
        dev: openwrt
        env: prod
      targets:
      - 192.168.10.1:9100
